label_mapping = {
  "Acne": "Mụn trứng cá",
  "Actinic_Keratosis": "Dày sừng quang hóa",
  "Benign_tumors": "U lành tính",
  "Bullous": "Bệnh bóng nước",
  "DrugEruption": "Phản ứng do thuốc",
  "Eczema": "Chàm",
  "Infestations_Bites": "Ký sinh trùng/Côn trùng cắn",
  "Lichen": "Lichen",
  "Moles": "Nốt ruồi",
  "Psoriasis": "Vảy nến",
  "Rosacea": "Chứng đỏ mặt",
  "Seborrh_Keratoses": "Dày sừng bã nhờn",
  "SkinCancer": "Ung thư da",
  "Sun_Sunlight_Damage": "Tổn thương do ánh nắng",
  "Tinea": "Bệnh nấm da",
  "Unknown_Normal": "Da bình thường/Chưa xác định",
  "Vascular_Tumors": "U mạch máu",
  "Vasculitis": "Viêm mạch máu",
  "Vitiligo": "Bạch biến",
  "Warts": "Mụn cóc",
  "Urticaria": "Mề đay",
  "Varicella": "Thủy đậu",
  "Herpes_Zoster": "Thủy đậu lở",
}