# Generated by Django 4.2.20 on 2025-04-18 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Disease",
            fields=[
                ("name", models.CharField(max_length=255)),
                ("definition", models.TextField()),
                ("symptoms", models.TextField()),
                ("causes", models.TextField()),
                ("treatments", models.TextField()),
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "verbose_name": "Disease",
                "verbose_name_plural": "Diseases",
                "db_table": "disease",
            },
        ),
    ]
