# Generated by Django 4.2.20 on 2025-04-22 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialogflow_webhook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='disease',
            table='diseases',
        ),
    ]
